steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        asia-southeast2-docker.pkg.dev/jalan-kerja-dev/jalankerja/$_SERVICE_NAME:$COMMIT_SHA
      - "--build-arg"
      - "APP_ENV=$_APP_ENV"
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-southeast2-docker.pkg.dev/jalan-kerja-dev/jalankerja/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=asia-southeast2-docker.pkg.dev/jalan-kerja-dev/jalankerja/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    asia-southeast2-docker.pkg.dev/jalan-kerja-dev/jalankerja/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: asia-southeast2
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=876f929d-bdc9-4fdf-8d95-d4450e055039
  _TRIGGER_ID: 876f929d-bdc9-4fdf-8d95-d4450e055039
  _SERVICE_NAME: jk-react
  _APP_ENV: dev
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - smartlink-hris-backend
